package app

import (
	"database/sql"
	"errors"
	"flow/internal/flowdb"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// cmdUpdate dispatches `flow update task|project`. The command is the
// canonical lane for in-place field edits — including legacy field
// setters (priority, due-date, waiting) that used to have their own
// top-level mini-commands.
func cmdUpdate(args []string) int {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "error: update requires 'task' or 'project' and a ref")
		return 2
	}
	switch args[0] {
	case "task":
		return cmdUpdateTask(args[1:])
	case "project":
		return cmdUpdateProject(args[1:])
	case "playbook":
		return cmdUpdatePlaybook(args[1:])
	}
	fmt.Fprintf(os.Stderr, "error: unknown update target %q (expected 'task', 'project', or 'playbook')\n", args[0])
	return 2
}

// validateRenameSlug rejects empty / path-separator-containing slugs.
// Slug format beyond that is intentionally lax to match `flow add`'s
// --slug acceptance (any non-empty string the user types is allowed).
func validateRenameSlug(s string) error {
	s = strings.TrimSpace(s)
	if s == "" {
		return fmt.Errorf("--slug cannot be empty")
	}
	if strings.ContainsAny(s, `/\`) {
		return fmt.Errorf("--slug must not contain path separators: %q", s)
	}
	return nil
}

// renameEntityDir moves ~/.flow/<entityDir>/<oldSlug>/ to <newSlug>/.
// Returns nil if the old dir doesn't exist (rename happened before any
// FS state existed — e.g. a freshly-created entity). Errors if the new
// dir already exists, since silently merging would obscure data.
func renameEntityDir(entityDir, oldSlug, newSlug string) error {
	if oldSlug == newSlug {
		return nil
	}
	root, err := flowRoot()
	if err != nil {
		return err
	}
	oldPath := filepath.Join(root, entityDir, oldSlug)
	newPath := filepath.Join(root, entityDir, newSlug)
	if _, err := os.Stat(oldPath); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat %s: %w", oldPath, err)
	}
	if _, err := os.Stat(newPath); err == nil {
		return fmt.Errorf("target dir %s already exists; refusing to overwrite", newPath)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat %s: %w", newPath, err)
	}
	if err := os.Rename(oldPath, newPath); err != nil {
		return fmt.Errorf("rename %s -> %s: %w", oldPath, newPath, err)
	}
	return nil
}

// sessionUUIDRe mirrors claude's --session-id contract: standard v4
// UUID, lowercase hex, with the version/variant bits enforced.
var sessionUUIDRe = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)

// sessionAnyUUIDRe accepts UUID-shaped ids generated by agent hosts that do
// not use Claude's v4 session-id contract. Codex currently exposes a
// CODEX_THREAD_ID with a UUID-shaped value that may be v7.
var sessionAnyUUIDRe = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

// cmdUpdateTask implements `flow update task <ref> [--work-dir <path>]
// [--mkdir] [--status <s>] [--assignee <name>] [--due-date <date>]
// [--parent <slug>] [--waiting ...] [--tag ...]`. At least one
// field-changing flag must be given.
//
// Status accepts any of backlog|in-progress|done. The session_id
// invariant (only backlog may have NULL session_id) is enforced
// here: setting --status to a non-backlog value on a task without a
// session_id errors with a pointer to `flow do` / `flow do --here`,
// which are the supported paths to attach a session.
//
// There is no --session-id flag here: that lane was removed in
// favor of `flow do --here` (in-session bind via
// $CLAUDE_CODE_SESSION_ID), which prevents wrong-session attachment
// by construction.
func cmdUpdateTask(args []string) int {
	if len(args) < 1 {
		fmt.Fprintln(os.Stderr, "error: update task requires a task ref")
		return 2
	}
	ref := args[0]
	fs := flagSet("update task")
	newSlug := fs.String("slug", "", "new slug (renames the task; cascades to child tasks, tags, PR links)")
	newName := fs.String("name", "", "new display name")
	workDir := fs.String("work-dir", "", "new absolute work directory")
	mkdir := fs.Bool("mkdir", false, "create --work-dir if it does not exist")
	status := fs.String("status", "", "new status: backlog|in-progress|done")
	priority := fs.String("priority", "", "new priority: high|medium|low")
	assignee := fs.String("assignee", "", "new assignee (use \"\" to keep, --clear-assignee to clear)")
	clearAssignee := fs.Bool("clear-assignee", false, "clear the assignee (back to default = self)")
	dueDate := fs.String("due-date", "", "new due date (YYYY-MM-DD, today, tomorrow, monday, 3d)")
	clearDue := fs.Bool("clear-due", false, "clear the due date")
	var addParents stringSliceFlag
	fs.Var(&addParents, "parent", "add a parent task slug (this task depends on the parent; repeatable: --parent foo --parent bar)")
	var removeParents stringSliceFlag
	fs.Var(&removeParents, "remove-parent", "remove a parent task slug (repeatable)")
	clearParent := fs.Bool("clear-parent", false, "clear ALL parent task links")
	waiting := fs.String("waiting", "", "set waiting_on freeform note (\"<who or what>\")")
	clearWaiting := fs.Bool("clear-waiting", false, "clear waiting_on")
	var addTags stringSliceFlag
	fs.Var(&addTags, "tag", "add a tag (repeatable: --tag foo --tag bar)")
	var removeTags stringSliceFlag
	fs.Var(&removeTags, "remove-tag", "remove a tag (repeatable)")
	clearTags := fs.Bool("clear-tags", false, "remove all tags from the task")
	if err := fs.Parse(args[1:]); err != nil {
		return 2
	}
	anyField := *newSlug != "" || *newName != "" ||
		*workDir != "" || *status != "" || *priority != "" ||
		*assignee != "" || *clearAssignee || *dueDate != "" || *clearDue ||
		len(addParents) > 0 || len(removeParents) > 0 || *clearParent ||
		*waiting != "" || *clearWaiting ||
		len(addTags) > 0 || len(removeTags) > 0 || *clearTags
	if !anyField {
		fmt.Fprintln(os.Stderr, "error: give at least one of --slug, --name, --work-dir, --status, --priority, --assignee, --clear-assignee, --due-date, --clear-due, --parent, --remove-parent, --clear-parent, --waiting, --clear-waiting, --tag, --remove-tag, --clear-tags")
		return 2
	}

	if *newSlug != "" {
		if err := validateRenameSlug(*newSlug); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			return 2
		}
	}

	if *status != "" && !isValidStatus(*status) {
		fmt.Fprintf(os.Stderr,
			"error: --status must be backlog|in-progress|done (got %q)\n", *status)
		return 2
	}

	if *priority != "" && !isValidPriority(*priority) {
		fmt.Fprintf(os.Stderr,
			"error: --priority must be high|medium|low (got %q)\n", *priority)
		return 2
	}

	if *clearAssignee && *assignee != "" {
		fmt.Fprintln(os.Stderr, "error: --assignee and --clear-assignee are mutually exclusive")
		return 2
	}
	if *clearDue && *dueDate != "" {
		fmt.Fprintln(os.Stderr, "error: --due-date and --clear-due are mutually exclusive")
		return 2
	}
	if *clearParent && (len(addParents) > 0 || len(removeParents) > 0) {
		fmt.Fprintln(os.Stderr, "error: --clear-parent and --parent/--remove-parent are mutually exclusive (clear-parent removes everything)")
		return 2
	}
	if *clearWaiting && *waiting != "" {
		fmt.Fprintln(os.Stderr, "error: --waiting and --clear-waiting are mutually exclusive")
		return 2
	}
	if *clearTags && len(removeTags) > 0 {
		fmt.Fprintln(os.Stderr, "error: --clear-tags and --remove-tag are mutually exclusive (clear-tags removes everything anyway)")
		return 2
	}

	var absWorkDir string
	if *workDir != "" {
		abs, err := resolveWorkDir(*workDir, *mkdir)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			return 1
		}
		absWorkDir = abs
	}

	var dueParsed string
	if *dueDate != "" {
		d, err := parseDueDate(*dueDate, time.Now())
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: --due-date: %v\n", err)
			return 2
		}
		dueParsed = d.Format("2006-01-02")
	}

	dbPath, err := flowDBPath()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}
	db, err := flowdb.OpenDB(dbPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: open db: %v\n", err)
		return 1
	}
	defer db.Close()

	task, err := ResolveTask(db, ref, true)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			fmt.Fprintf(os.Stderr, "error: task %q not found\n", ref)
			return 1
		}
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}

	// Rename first so subsequent field updates operate on the new slug.
	// FS dir move happens after the DB cascade succeeds; if FS rename
	// fails after DB commit we leave a recoverable inconsistency (DB
	// points at new slug, dir is still under old slug).
	if *newSlug != "" && *newSlug != task.Slug {
		if err := flowdb.RenameTask(db, task.Slug, *newSlug); err != nil {
			if errors.Is(err, flowdb.ErrSlugTaken) {
				fmt.Fprintf(os.Stderr, "error: task slug %q is already taken\n", *newSlug)
				return 1
			}
			fmt.Fprintf(os.Stderr, "error: rename task: %v\n", err)
			return 1
		}
		if err := renameEntityDir("tasks", task.Slug, *newSlug); err != nil {
			fmt.Fprintf(os.Stderr, "warning: db slug updated but dir rename failed: %v\n", err)
		}
		fmt.Printf("slug → %s\n", *newSlug)
		task.Slug = *newSlug
	}

	now := flowdb.NowISO()
	if *newName != "" {
		if _, err := db.Exec(
			`UPDATE tasks SET name=?, updated_at=? WHERE slug=?`,
			*newName, now, task.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update name: %v\n", err)
			return 1
		}
		fmt.Printf("name → %s\n", *newName)
	}
	if absWorkDir != "" {
		if _, err := db.Exec(
			`UPDATE tasks SET work_dir=?, updated_at=? WHERE slug=?`,
			absWorkDir, now, task.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update work_dir: %v\n", err)
			return 1
		}
		fmt.Printf("work_dir → %s\n", absWorkDir)
	}
	if *status != "" {
		// Session-id invariant: any non-backlog status requires a
		// session_id. Enforced at the DB level via CHECK, but we error
		// here with a friendly pointer instead of letting the user see
		// a raw constraint violation.
		if *status != "backlog" && (!task.SessionID.Valid || task.SessionID.String == "") {
			fmt.Fprintf(os.Stderr,
				"error: cannot set status to %q without a session_id.\n"+
					"  to start work on this task, run one of:\n"+
					"    flow do %s          (spawns a new agent session in a new tab)\n"+
					"    flow do --here %s   (binds this Claude/Codex session to the task)\n",
				*status, task.Slug, task.Slug)
			return 1
		}
		if _, err := db.Exec(
			`UPDATE tasks SET status=?,
			 status_changed_at = CASE WHEN status != ? THEN ? ELSE status_changed_at END,
			 updated_at=? WHERE slug=?`,
			*status, *status, now, now, task.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update status: %v\n", err)
			return 1
		}
		fmt.Printf("status → %s\n", *status)
	}
	if *priority != "" {
		if _, err := db.Exec(
			`UPDATE tasks SET priority=?, updated_at=? WHERE slug=?`,
			*priority, now, task.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update priority: %v\n", err)
			return 1
		}
		fmt.Printf("priority → %s\n", *priority)
	}
	for _, p := range addParents {
		parentTask, err := ResolveTask(db, p, true)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				fmt.Fprintf(os.Stderr, "error: parent task %q not found\n", p)
				return 1
			}
			fmt.Fprintf(os.Stderr, "error: resolve parent %q: %v\n", p, err)
			return 1
		}
		if parentTask.Slug == task.Slug {
			fmt.Fprintln(os.Stderr, "error: task cannot depend on itself")
			return 2
		}
		if err := flowdb.AddTaskParent(db, task.Slug, parentTask.Slug); err != nil {
			fmt.Fprintf(os.Stderr, "error: add parent %q: %v\n", parentTask.Slug, err)
			return 1
		}
		fmt.Printf("parent + %s\n", parentTask.Slug)
	}
	for _, p := range removeParents {
		parentTask, err := ResolveTask(db, p, true)
		if err != nil {
			// Removal targets may have been deleted/renamed — fall through to
			// the raw slug so the user can still clear stale rows.
			if !errors.Is(err, sql.ErrNoRows) {
				fmt.Fprintf(os.Stderr, "error: resolve parent %q: %v\n", p, err)
				return 1
			}
			parentTask = &flowdb.Task{Slug: p}
		}
		if err := flowdb.RemoveTaskParent(db, task.Slug, parentTask.Slug); err != nil {
			fmt.Fprintf(os.Stderr, "error: remove parent %q: %v\n", parentTask.Slug, err)
			return 1
		}
		fmt.Printf("parent − %s\n", parentTask.Slug)
	}
	if *clearParent {
		if err := flowdb.ClearTaskParents(db, task.Slug); err != nil {
			fmt.Fprintf(os.Stderr, "error: clear parents: %v\n", err)
			return 1
		}
		fmt.Println("parents cleared")
	}
	if len(addParents) > 0 || len(removeParents) > 0 || *clearParent {
		if _, err := db.Exec(`UPDATE tasks SET updated_at=? WHERE slug=?`, now, task.Slug); err != nil {
			fmt.Fprintf(os.Stderr, "error: bump updated_at: %v\n", err)
			return 1
		}
	}
	if *waiting != "" {
		if _, err := db.Exec(
			`UPDATE tasks SET waiting_on=?, updated_at=? WHERE slug=?`,
			*waiting, now, task.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update waiting: %v\n", err)
			return 1
		}
		fmt.Printf("waiting_on → %s\n", *waiting)
	}
	if *clearWaiting {
		if _, err := db.Exec(
			`UPDATE tasks SET waiting_on=NULL, updated_at=? WHERE slug=?`,
			now, task.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: clear waiting: %v\n", err)
			return 1
		}
		fmt.Println("waiting_on cleared")
	}
	if *assignee != "" {
		if _, err := db.Exec(
			`UPDATE tasks SET assignee=?, updated_at=? WHERE slug=?`,
			*assignee, now, task.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update assignee: %v\n", err)
			return 1
		}
		fmt.Printf("assignee → %s\n", *assignee)
	}
	if *clearAssignee {
		if _, err := db.Exec(
			`UPDATE tasks SET assignee=NULL, updated_at=? WHERE slug=?`,
			now, task.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: clear assignee: %v\n", err)
			return 1
		}
		fmt.Println("assignee cleared")
	}
	if dueParsed != "" {
		if _, err := db.Exec(
			`UPDATE tasks SET due_date=?, updated_at=? WHERE slug=?`,
			dueParsed, now, task.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update due_date: %v\n", err)
			return 1
		}
		fmt.Printf("due_date → %s\n", dueParsed)
	}
	if *clearDue {
		if _, err := db.Exec(
			`UPDATE tasks SET due_date=NULL, updated_at=? WHERE slug=?`,
			now, task.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: clear due_date: %v\n", err)
			return 1
		}
		fmt.Println("due_date cleared")
	}
	if *clearTags {
		if err := flowdb.ClearTaskTags(db, task.Slug); err != nil {
			fmt.Fprintf(os.Stderr, "error: clear tags: %v\n", err)
			return 1
		}
		fmt.Println("tags cleared")
	}
	for _, raw := range removeTags {
		t := flowdb.NormalizeTag(raw)
		if t == "" {
			fmt.Fprintf(os.Stderr, "error: tag %q is empty after normalization\n", raw)
			return 2
		}
		if err := flowdb.RemoveTaskTag(db, task.Slug, t); err != nil {
			fmt.Fprintf(os.Stderr, "error: remove tag: %v\n", err)
			return 1
		}
		fmt.Printf("tag - %s\n", t)
	}
	for _, raw := range addTags {
		t := flowdb.NormalizeTag(raw)
		if t == "" {
			fmt.Fprintf(os.Stderr, "error: tag %q is empty after normalization\n", raw)
			return 2
		}
		if err := flowdb.AddTaskTag(db, task.Slug, t); err != nil {
			fmt.Fprintf(os.Stderr, "error: add tag: %v\n", err)
			return 1
		}
		fmt.Printf("tag + %s\n", t)
	}
	return 0
}

// stringSliceFlag adapts a *[]string into a flag.Value so the same
// flag name can be passed multiple times and accumulate. Used for
// repeatable `--tag` / `--remove-tag` on `flow update task`.
type stringSliceFlag []string

func (s *stringSliceFlag) String() string {
	if s == nil {
		return ""
	}
	return strings.Join(*s, ",")
}

func (s *stringSliceFlag) Set(v string) error {
	*s = append(*s, v)
	return nil
}

// isValidStatus checks the task status enum.
func isValidStatus(s string) bool {
	return s == "backlog" || s == "in-progress" || s == "done"
}

// cmdUpdateProject implements `flow update project <ref> [--slug <s>]
// [--name <n>] [--work-dir <path>] [--mkdir] [--priority <p>]`. --slug
// renames the project and cascades to tasks.project_slug and
// playbooks.project_slug; the ~/.flow/projects/<slug>/ directory moves
// to match.
func cmdUpdateProject(args []string) int {
	if len(args) < 1 {
		fmt.Fprintln(os.Stderr, "error: update project requires a project ref")
		return 2
	}
	ref := args[0]
	fs := flagSet("update project")
	newSlug := fs.String("slug", "", "new slug (renames the project; cascades to tasks/playbooks)")
	newName := fs.String("name", "", "new display name")
	workDir := fs.String("work-dir", "", "new absolute work directory")
	mkdir := fs.Bool("mkdir", false, "create --work-dir if it does not exist")
	priority := fs.String("priority", "", "new priority: high|medium|low")
	if err := fs.Parse(args[1:]); err != nil {
		return 2
	}
	if *newSlug == "" && *newName == "" && *workDir == "" && *priority == "" {
		fmt.Fprintln(os.Stderr, "error: give at least one of --slug, --name, --work-dir, --priority")
		return 2
	}
	if *priority != "" && !isValidPriority(*priority) {
		fmt.Fprintf(os.Stderr,
			"error: --priority must be high|medium|low (got %q)\n", *priority)
		return 2
	}
	if *newSlug != "" {
		if err := validateRenameSlug(*newSlug); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			return 2
		}
	}

	var absWorkDir string
	if *workDir != "" {
		abs, err := resolveWorkDir(*workDir, *mkdir)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			return 1
		}
		absWorkDir = abs
	}

	dbPath, err := flowDBPath()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}
	db, err := flowdb.OpenDB(dbPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: open db: %v\n", err)
		return 1
	}
	defer db.Close()

	p, err := ResolveProject(db, ref, true)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			fmt.Fprintf(os.Stderr, "error: project %q not found\n", ref)
			return 1
		}
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}

	if *newSlug != "" && *newSlug != p.Slug {
		if err := flowdb.RenameProject(db, p.Slug, *newSlug); err != nil {
			if errors.Is(err, flowdb.ErrSlugTaken) {
				fmt.Fprintf(os.Stderr, "error: project slug %q is already taken\n", *newSlug)
				return 1
			}
			fmt.Fprintf(os.Stderr, "error: rename project: %v\n", err)
			return 1
		}
		if err := renameEntityDir("projects", p.Slug, *newSlug); err != nil {
			fmt.Fprintf(os.Stderr, "warning: db slug updated but dir rename failed: %v\n", err)
		}
		fmt.Printf("slug → %s\n", *newSlug)
		p.Slug = *newSlug
	}

	now := flowdb.NowISO()
	if *newName != "" {
		if _, err := db.Exec(
			`UPDATE projects SET name=?, updated_at=? WHERE slug=?`,
			*newName, now, p.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update name: %v\n", err)
			return 1
		}
		fmt.Printf("name → %s\n", *newName)
	}
	if absWorkDir != "" {
		if _, err := db.Exec(
			`UPDATE projects SET work_dir=?, updated_at=? WHERE slug=?`,
			absWorkDir, now, p.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update work_dir: %v\n", err)
			return 1
		}
		fmt.Printf("work_dir → %s\n", absWorkDir)
	}
	if *priority != "" {
		if _, err := db.Exec(
			`UPDATE projects SET priority=?, updated_at=? WHERE slug=?`,
			*priority, now, p.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update priority: %v\n", err)
			return 1
		}
		fmt.Printf("priority → %s\n", *priority)
	}
	return 0
}

// cmdUpdatePlaybook implements `flow update playbook <ref> [--slug <s>]
// [--name <n>] [--work-dir <path>] [--mkdir]`. --slug renames the
// playbook and cascades to tasks.playbook_slug (playbook-run tasks).
// The ~/.flow/playbooks/<slug>/ directory moves to match. Existing
// playbook-run task brief.md snapshots are NOT rewritten — they remain
// frozen at run time and may still reference the old slug in their
// stamped contents; that is by design.
func cmdUpdatePlaybook(args []string) int {
	if len(args) < 1 {
		fmt.Fprintln(os.Stderr, "error: update playbook requires a playbook ref")
		return 2
	}
	ref := args[0]
	fs := flagSet("update playbook")
	newSlug := fs.String("slug", "", "new slug (renames the playbook; cascades to playbook-run tasks)")
	newName := fs.String("name", "", "new display name")
	workDir := fs.String("work-dir", "", "new absolute work directory")
	mkdir := fs.Bool("mkdir", false, "create --work-dir if it does not exist")
	if err := fs.Parse(args[1:]); err != nil {
		return 2
	}
	if *newSlug == "" && *newName == "" && *workDir == "" {
		fmt.Fprintln(os.Stderr, "error: give at least one of --slug, --name, --work-dir")
		return 2
	}
	if *newSlug != "" {
		if err := validateRenameSlug(*newSlug); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			return 2
		}
	}

	var absWorkDir string
	if *workDir != "" {
		abs, err := resolveWorkDir(*workDir, *mkdir)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			return 1
		}
		absWorkDir = abs
	}

	dbPath, err := flowDBPath()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}
	db, err := flowdb.OpenDB(dbPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: open db: %v\n", err)
		return 1
	}
	defer db.Close()

	pb, err := ResolvePlaybook(db, ref, true)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			fmt.Fprintf(os.Stderr, "error: playbook %q not found\n", ref)
			return 1
		}
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}

	if *newSlug != "" && *newSlug != pb.Slug {
		if err := flowdb.RenamePlaybook(db, pb.Slug, *newSlug); err != nil {
			if errors.Is(err, flowdb.ErrSlugTaken) {
				fmt.Fprintf(os.Stderr, "error: playbook slug %q is already taken\n", *newSlug)
				return 1
			}
			fmt.Fprintf(os.Stderr, "error: rename playbook: %v\n", err)
			return 1
		}
		if err := renameEntityDir("playbooks", pb.Slug, *newSlug); err != nil {
			fmt.Fprintf(os.Stderr, "warning: db slug updated but dir rename failed: %v\n", err)
		}
		fmt.Printf("slug → %s\n", *newSlug)
		pb.Slug = *newSlug
	}

	now := flowdb.NowISO()
	if *newName != "" {
		if _, err := db.Exec(
			`UPDATE playbooks SET name=?, updated_at=? WHERE slug=?`,
			*newName, now, pb.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update name: %v\n", err)
			return 1
		}
		fmt.Printf("name → %s\n", *newName)
	}
	if absWorkDir != "" {
		if _, err := db.Exec(
			`UPDATE playbooks SET work_dir=?, updated_at=? WHERE slug=?`,
			absWorkDir, now, pb.Slug,
		); err != nil {
			fmt.Fprintf(os.Stderr, "error: update work_dir: %v\n", err)
			return 1
		}
		fmt.Printf("work_dir → %s\n", absWorkDir)
	}
	return 0
}

// parseDueDate converts a human-friendly date expression to a time.Time.
// Accepts: YYYY-MM-DD, today, tomorrow, weekday names (next occurrence),
// Nd (N days from now). `now` is passed in for testability.
//
// Lives here (rather than in a setter command) because the legacy
// `flow due` / `flow waiting` / `flow priority` mini-commands have
// been folded into `flow update task`. parseDueDate is shared with
// `flow add task --due`.
func parseDueDate(s string, now time.Time) (time.Time, error) {
	s = strings.TrimSpace(strings.ToLower(s))

	switch s {
	case "today":
		y, m, d := now.Date()
		return time.Date(y, m, d, 0, 0, 0, 0, now.Location()), nil
	case "tomorrow":
		y, m, d := now.AddDate(0, 0, 1).Date()
		return time.Date(y, m, d, 0, 0, 0, 0, now.Location()), nil
	}

	weekdays := map[string]time.Weekday{
		"sunday": time.Sunday, "monday": time.Monday,
		"tuesday": time.Tuesday, "wednesday": time.Wednesday,
		"thursday": time.Thursday, "friday": time.Friday,
		"saturday": time.Saturday,
	}
	if target, ok := weekdays[s]; ok {
		current := now.Weekday()
		delta := int(target) - int(current)
		if delta <= 0 {
			delta += 7
		}
		d := now.AddDate(0, 0, delta)
		y, m, dd := d.Date()
		return time.Date(y, m, dd, 0, 0, 0, 0, now.Location()), nil
	}

	if strings.HasSuffix(s, "d") {
		numStr := strings.TrimSuffix(s, "d")
		var n int
		if _, err := fmt.Sscanf(numStr, "%d", &n); err == nil && n >= 0 {
			d := now.AddDate(0, 0, n)
			y, m, dd := d.Date()
			return time.Date(y, m, dd, 0, 0, 0, 0, now.Location()), nil
		}
	}

	if t, err := time.ParseInLocation("2006-01-02", s, now.Location()); err == nil {
		return t, nil
	}

	return time.Time{}, fmt.Errorf("unrecognized date %q (want YYYY-MM-DD, today, tomorrow, monday..sunday, Nd)", s)
}

