package steering

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// htmlCommentRe strips HTML comments from the persona file so editing guidance
// in the seeded template (and any the operator adds) never leaks into prompts.
var htmlCommentRe = regexp.MustCompile(`(?s)<!--.*?-->`)

// DefaultPersonaMarkdown is the built-in voice: a sensible human default that is
// ALWAYS the floor — applied whenever no custom persona is saved (not only on
// fresh `flow init`) and pre-filled into the editor so the operator can tweak
// it. The HTML comment is editing guidance, stripped before injection. Shared by
// init (seeding), the server (GET pre-fill), and OperatorVoice (injection
// fallback) so there is one source of truth.
const DefaultPersonaMarkdown = `<!--
flow voice — how flow writes Slack/GitHub replies on your behalf.
Edit the lines below so drafts and sends sound like YOU. Anything inside these
HTML comments is ignored; everything else is injected into the writing prompts,
so keep it concrete: tone, phrasing, greetings, sign-offs, and do/don'ts.
-->

Write like a real person — warm, direct, and concise. Plain language, no
corporate filler, and never an AI-assistant or support-bot tone. Match the other
person's formality and mirror how they write. Keep replies short; don't
over-explain or hedge. Never add a signature, disclaimer, or "Sent via …" footer.
`

// StripPersonaComments removes editing-guidance HTML comments and trims — i.e.
// the editable voice content, without the static notes. Exported so the server
// can return just the voice to the editor (the notes are shown statically in the
// UI, not inside the editable box).
func StripPersonaComments(s string) string {
	return strings.TrimSpace(htmlCommentRe.ReplaceAllString(s, ""))
}

// DefaultVoiceText is the built-in default with guidance comments removed — the
// editable voice the UI pre-fills when nothing is saved.
func DefaultVoiceText() string { return StripPersonaComments(DefaultPersonaMarkdown) }

// flowRootDir resolves flow's data root the way the rest of flow does: $FLOW_ROOT
// when set, else ~/.flow. Tests override $FLOW_ROOT / $HOME.
func flowRootDir() string {
	if r := strings.TrimSpace(os.Getenv("FLOW_ROOT")); r != "" {
		return r
	}
	if home, err := os.UserHomeDir(); err == nil && strings.TrimSpace(home) != "" {
		return filepath.Join(home, ".flow")
	}
	return ".flow"
}

// PersonaPath is the operator's voice/persona markdown file under the flow root.
func PersonaPath() string { return filepath.Join(flowRootDir(), "persona.md") }

// OperatorVoice returns the operator's configured voice/persona text (trimmed,
// length-capped), or "" when unset. This is the human-voice spec injected into
// drafting and sending prompts so replies read as if the operator wrote them.
func OperatorVoice() string {
	v := ""
	if data, err := os.ReadFile(PersonaPath()); err == nil {
		v = StripPersonaComments(string(data))
	}
	// No saved (or empty) persona → fall back to the built-in default so a
	// sensible human voice is always in effect, even on installs that predate
	// the `flow init` seed.
	if v == "" {
		v = DefaultVoiceText()
	}
	if len(v) > 4000 {
		v = strings.TrimSpace(v[:4000])
	}
	return v
}

// OperatorVoiceDirective is the prompt block that injects the operator's voice
// into a drafting/sending prompt. Empty when no persona is configured, so it is
// a no-op for operators who haven't set one. Exported so EVERY drafting path —
// the stateless triage/send steps here AND the per-channel steerer session brief
// in internal/server — injects the same voice from one source of truth, rather
// than only name-dropping "the operator's voice" without the actual text.
func OperatorVoiceDirective() string {
	v := OperatorVoice()
	if v == "" {
		return ""
	}
	return "\nOPERATOR VOICE — any draft or reply MUST read as if the operator personally typed it. Match this voice: tone, phrasing, greeting/sign-off habits, formality, capitalization, emoji use. Do NOT sound like an AI assistant or a support bot, and never add a signature or any \"Sent via …\" / \"Generated by …\" footer. The operator's voice:\n" + v + "\n"
}

// operatorVoiceDirective is the unexported alias kept for the in-package callers
// (triage, send_reply) so their call sites stay unchanged.
func operatorVoiceDirective() string { return OperatorVoiceDirective() }
